# Güncel TYT ve AYT Konuları

TYT_TOPICS = {
    "Türkçe": [
        "Sözcükte Anlam",
        "Cümlede Anlam",
        "Paragrafta Anlam",
        "Anlatım Biçimleri",
        "Ses Bilgisi",
        "Yazım Kuralları",
        "Noktalama İşaretleri",
        "Sözcükte Yapı",
        "Sözcük Türleri",
        "Edat-Bağlaç-Ünlem",
        "Fiiller",
        "Ek Fiil",
        "Fiilde Çatı",
        "Fiilimsi",
        "Cümlelerin Öğeleri",
        "Cümle Türleri",
        "Anlatım Bozuklukları"
    ],
    "Matematik": [
        "Sayılar",
        "Sayı Basamakları",
        "Bölme ve Bölünebilme",
        "OBEB-OKEK",
        "Rasyonel Sayılar",
        "Basit Eşitsizlikler",
        "Mutlak Değer",
        "Üslü Sayılar",
        "Köklü Sayılar",
        "Oranlar-Orantı",
        "Denklemler",
        "Problem Çözme",
        "Kümeler",
        "Fonksiyonlar",
        "Permütasyon",
        "Kombinasyon",
        "Binom",
        "Olasılık",
        "İstatistik",
        "2. Dereceden Denklemler",
        "Karmaşık Sayılar",
        "Polinomlar"
    ],
    "Geometri": [
        "Doğruda ve Üçgende Açılar",
        "Üçgende Açı-Kenar Bağıntıları",
        "Üçgende Benzerlik",
        "Üçgende Açıortay-Kenarortay",
        "Dik Üçgen",
        "İkizkenar Üçgen",
        "Eşkenar Üçgen",
        "Üçgenlerde Alan",
        "Çokgenler",
        "Dörtgenler",
        "Yamuk-Paralelkenar",
        "Eşkenar Dörtgen",
        "Dikdörtgen",
        "Kare",
        "Deltoid",
        "Çemberde Açılar",
        "Çemberde Uzunluk",
        "Dairenin Çevresi ve Alanı",
        "Doğrunun Analitik İncelenmesi",
        "Çemberin Analitik İncelenmesi",
        "Katı Cisimler"
    ],
    "Tarih": [
        "Tarih Bilimine Giriş",
        "Uygarlığın Doğuşu ve İlk Uygarlıklar",
        "İlk Türk Devletleri",
        "İslam Tarihi ve Uygarlığı",
        "Türk-İslam Devletleri",
        "Türkler'in İslamiyeti Kabulü",
        "Türkiye Tarihi",
        "Beylikten Devlete (1300-1453)",
        "Dünya Gücü: Osmanlı Devleti",
        "Osmanlı Duraklama Dönemi",
        "Gerileme Devri (1699–1792)",
        "Arayış Yılları (17. Yüzyıl)",
        "Avrupa ve Osmanlı Devleti (18. Yüzyıl)",
        "En Uzun Yüzyıl (1800-1922)",
        "20. Yüzyıl Başlarında Osmanlı Devleti",
        "XIX. YY Osmanlı Devleti",
        "1. Dünya Savaşı – Milli Mücadeleye Hazırlık Dönemi",
        "Kurtuluş Savaşında Cepheler",
        "Türk İnkılabı",
        "Atatürkçülük ve Atatürk İlkeleri",
        "Türk Dış Politikası"
    ],
    "Coğrafya": [
        "İnsan ve Coğrafya",
        "Dünya'nın Şekli ve Hareketleri",
        "Harita Bilgisi",
        "Coğrafi Konum",
        "Dünya'nın Yapısı ve Oluşum Süreci",
        "Su Kaynakları-Toprak-Bitkiler",
        "İklim Bilgisi",
        "Nüfus-Türkiye'de Nüfus",
        "Göç",
        "Ekonomik Faaliyetler",
        "Ülkeler ve Bölgeler",
        "Çevre ve Toplum"
    ],
    "Felsefe": [
        "Felsefe'nin Alanı",
        "Bilgi Felsefesi",
        "Bilim Felsefesi",
        "Varlık Felsefesi",
        "Ahlak Felsefesi",
        "Siyaset Felsefesi",
        "Sanat Felsefesi",
        "Din Felsefesi"
    ],
    "Din Kültürü": [
        "İnsan ve Din (İnanç)",
        "İbadet",
        "Hz. Muhammed'in Hayatı",
        "Vahiy ve Akıl",
        "İslam Düşüncesi ve Yorumu",
        "İslamda Değerler, Sanat ve Laiklik",
        "Yaşayan Dinler"
    ],
    "Fizik": [
        "Fizik Bilimine Giriş",
        "Madde ve Özellikleri",
        "Sıvıların Kaldırma Kuvveti",
        "Basınç",
        "Isı, Sıcaklık ve Genleşme",
        "Hareket ve Kuvvet",
        "Dinamik",
        "İş, Güç ve Enerji",
        "Elektrik",
        "Manyetizma",
        "Optik"
    ],
    "Kimya": [
        "Kimya Bilimi",
        "Atom ve Yapısı",
        "Periyodik Sistem",
        "Kimyasal Türler Arası Etkileşimler",
        "Asitler-Bazlar ve Tuzlar",
        "Doğa ve Kimya",
        "Kimyasal Tepkimeler",
        "Kimyanın Temel Yasaları",
        "Maddenin Halleri",
        "Karışımlar",
        "Endüstride ve Canlılarda Enerji",
        "Kimya Her Yerde"
    ],
    "Biyoloji": [
        "Canlıların Ortak Özellikleri",
        "Canlıların Temel Bileşenleri",
        "Hücre ve Organelleri",
        "Hücre Zarından Madde Geçişi",
        "Canlıların Sınıflandırılması",
        "Mitoz ve Eşeysiz Üreme",
        "Mayoz ve Eşeyli Üreme",
        "Kalıtım",
        "Ekosistem Ekolojisi",
        "Güncel Çevre Sorunları"
    ]
}

AYT_SAYISAL = {
    "Matematik": [
        "Temel Kavramlar",
        "Sayı Basamakları",
        "Bölme ve Bölünebilme",
        "EBOB - EKOK",
        "Rasyonel Sayılar",
        "Basit Eşitsizlikler",
        "Mutlak Değer",
        "Üslü Sayılar",
        "Köklü Sayılar",
        "Çarpanlara Ayırma",
        "Oran Orantı",
        "Denklem Çözme",
        "Problemler",
        "Kümeler",
        "Kartezyen Çarpım",
        "Mantık",
        "Fonksiyonlar",
        "Polinomlar",
        "2. Dereceden Denklemler",
        "Permütasyon ve Kombinasyon",
        "Binom ve Olasılık",
        "İstatistik",
        "Karmaşık Sayılar",
        "2. Dereceden Eşitsizlikler",
        "Parabol",
        "Trigonometri",
        "Logaritma",
        "Diziler",
        "Limit",
        "Türev",
        "İntegral"
    ],
    "Geometri": [
        "Doğruda ve Üçgende Açılar",
        "Dik ve Özel Üçgenler",
        "Dik Üçgende Trigonometrik Bağıntılar",
        "İkizkenar ve Eşkenar Üçgen",
        "Üçgende Alanlar",
        "Üçgende Açıortay Bağıntıları",
        "Üçgende Kenarortay Bağıntıları",
        "Üçgende Eşlik ve Benzerlik",
        "Üçgende Açı-Kenar Bağıntıları",
        "Çokgenler",
        "Dörtgenler",
        "Yamuk",
        "Paralelkenar",
        "Eşkenar Dörtgen - Deltoid",
        "Dikdörtgen",
        "Çemberde Açılar",
        "Çemberde Uzunluk",
        "Daire",
        "Prizmalar",
        "Piramitler",
        "Küre",
        "Koordinat Düzlemi ve Noktanın Analitiği",
        "Doğrunun Analitiği",
        "Tekrar Eden, Dönen ve Yansıyan Şekiller",
        "Dönüşümlerle Geometri",
        "Trigonometri",
        "Çemberin Analitiği"
    ],
    "Fizik": [
        "Vektörler",
        "Kuvvet, Tork ve Denge",
        "Kütle Merkezi",
        "Basit Makineler",
        "Hareket",
        "Newton'un Hareket Yasaları",
        "İş, Güç ve Enerji II",
        "Atışlar",
        "İtme ve Momentum",
        "Elektrik Alan ve Potansiyel",
        "Paralel Lehvhalar ve Sığa",
        "Manyetik Alan ve Manyetik Kuvvet",
        "İndüksiyon, Alternatif Akım ve Transformatörler",
        "Çembersel Hareket",
        "Kütle Çekim ve Kepler Yasaları",
        "Basit Harmonik Hareket",
        "Dalga Mekaniği ve Elektromanyetik Dalgalar",
        "Atom Modelleri",
        "Büyük Patlama ve Radyoaktivite",
        "Modern Fizik",
        "Modern Fiziğin Teknolojideki Uygulamaları"
    ],
    "Kimya": [
        "Modern Atom Teorisi",
        "Gazlar",
        "Sıvı Çözeltiler ve Çözünürlük",
        "Kimyasal Tepkimelerde Enerji",
        "Tepkimelerde Hız ve Denge",
        "Kimya ve Elektrik",
        "Karbon Kimyası",
        "Organik Kimya",
        "Enerji Kaynakları ve Bilimsel Gelişmeler"
    ],
    "Biyoloji": [
        "Sinir Sistemi",
        "Endokrin Sistem",
        "Duyu Organları",
        "Destek ve Hareket Sistemi",
        "Sindirim Sistemi",
        "Dolaşım ve Bağışıklık Sistemi",
        "Solunum Sistemi",
        "Ürener Sistem",
        "Üreme Sistemi ve Embriyonik Gelişim",
        "Komünite ve Popülasyon Ekolojisi",
        "Nükleik Asitler",
        "Genetik Şifre ve Protein Sentezi",
        "Canlılık ve Enerji",
        "Fotosentez ve Kemosentez",
        "Hücresel Solunum",
        "Bitki Biyolojisi",
        "Canlılar ve Çevre"
    ]
}

AYT_ESIT_AGIRLIK = {
    "Edebiyat": [
        "Anlam Bilgisi (Sözcükte, Cümlede ve Paragrafta Anlam)",
        "Edebi Bilgiler (Şiir Bilgisi)",
        "Edebi Bilgiler (Düz Yazı Türleri)",
        "İslamiyet Öncesi Türk Edebiyatı",
        "İslami Dönem İlk Dil ve Edebiyat Ürünleri",
        "Divan Edebiyatı",
        "Halk Edebiyatı",
        "Edebi Akımlar",
        "Tanzimat Edebiyatı",
        "Servetifünun Edebiyatı",
        "Fecr-i Ati Edebiyatı",
        "Milli Edebiyat",
        "Cumhuriyet Şiiri",
        "Cumhuriyet Romanı",
        "Cumhuriyet Dönemi",
        "Dünya Edebiyatı",
        "Çağdaş Türk Edebiyatı",
        "Eser Özetleri"
    ],
    "Tarih-1": [
        "Tarih Bilimine Giriş",
        "İlk Çağ Medeniyetleri",
        "İslam Öncesi Türk Tarihi",
        "İslam Tarihi ve Medeniyeti",
        "İlk Türk İslam Devletleri",
        "Türkiye Tarihi",
        "Orta Çağ'da Avrupa",
        "Beylikten Devlete",
        "Dünya Gücü: Osmanlı Devleti",
        "Arayış Yılları",
        "Yeni ve Yakın Çağ'da Avrupa",
        "Yüzyıl Değişim ve Diploması",
        "En Uzun Yüzyıl",
        "Osmanlı Kültür ve Medeniyeti",
        "Yüzyıl Başlarında Osmanlı Devleti",
        "Birinci Dünya Savaşı",
        "İnkılap Tarihi Tüm Konular",
        "Yüzyıl Başlarında Dünya",
        "İkinci Dünya Savaşı",
        "Soğuk Savaş Dönemi",
        "Yumuşama Dönemi",
        "Küreselleşen Dünya"
    ],
    "Coğrafya-1": [
        "Beşeri Sistemler",
        "Mekansal Bir Sentez: Türkiye",
        "Türkiye'de Tarım ve Hayvancılık",
        "Türkiye'nin Bölgeleri ve Bölgesel Kalkınma Projeleri",
        "Küresel Ortam: Bölgeler ve Ülkeler",
        "Ülkeler Coğrafyası",
        "Ekosistem ve Madde Döngüleri",
        "Çevre ve İnsan",
        "Doğal Afetler"
    ],
    "Matematik": AYT_SAYISAL["Matematik"],
    "Geometri": AYT_SAYISAL["Geometri"]
}

AYT_SOZEL = {
    "Edebiyat": AYT_ESIT_AGIRLIK["Edebiyat"],
    "Tarih-1": AYT_ESIT_AGIRLIK["Tarih-1"],
    "Coğrafya-1": AYT_ESIT_AGIRLIK["Coğrafya-1"]
}
